#ifndef ERR_CODES_H_INCLUDED
#define ERR_CODES_H_INCLUDED
enum errcodes_type_enum {__ERR_CODES_SUCCESS,__ERR_CODES_FAIL,__ERR_CODES_BIG_SIZE_INPUT,__ERR_CODES_INVALID_FILE};
#endif // ERR_CODES_H_INCLUDED
